Documents:
  path: /Users/eduardofgiovannini/Documents
Desktop:
  path: /Users/eduardofgiovannini/Desktop
Downloads:
  path: /Users/eduardofgiovannini/Downloads
Pictures:
  path: /Users/eduardofgiovannini/Pictures
Movies:
  path: /Users/eduardofgiovannini/Movies
Music:
  path: /Users/eduardofgiovannini/Music
CloudStorage:
  path: /Users/eduardofgiovannini/Library/CloudStorage
Volumes:
  path: /Volumes
