#!/bin/zsh
# ---------------------------------------------------------
#
# LifeOS Organizer
#
# Task: 02
#
# Purpose:
# Build reusable inventory framework.
#
# Safety:
#
# ✓ Read only
#
# ✓ No delete
#
# ✓ No rename
#
# ✓ No move
#
# ✓ No network
#
# ✓ No sudo
#
# Generated by Codex
#
# Reviewed by ChatGPT
#
# ---------------------------------------------------------

set -euo pipefail

PROJECT_DIR='/Users/eduardofgiovannini/Documents/GitHub/LifeOS-Organizer'
CONFIG_PATH="$PROJECT_DIR/config/inventory_targets.yaml"
TEMPLATE_PATH="$PROJECT_DIR/templates/inventory_report_template.md"
REPORT_PATH="$PROJECT_DIR/reports/02_inventory_engine.txt"
EXPECTED_TARGETS=(Documents Desktop Downloads Pictures Movies Music CloudStorage Volumes)
REQUIRED_PROJECT_DIRS=(docs scripts reports plans logs inventory templates config)

print_header() {
  print -- '---------------------------------------------------------'
  print
  print -- 'LifeOS Organizer'
  print
  print -- 'Task: 02'
  print
  print -- 'Purpose:'
  print -- 'Build reusable inventory framework.'
  print
  print -- 'Safety:'
  print
  print -- '✓ Read only'
  print
  print -- '✓ No delete'
  print
  print -- '✓ No rename'
  print
  print -- '✓ No move'
  print
  print -- '✓ No network'
  print
  print -- '✓ No sudo'
  print
  print -- 'Generated by Codex'
  print
  print -- 'Reviewed by ChatGPT'
  print
  print -- '---------------------------------------------------------'
}

section() {
  print
  print -- '=============================================================================='
  print -- "$1"
  print -- '=============================================================================='
}

failures=0
warnings=0

record_check() {
  local label="$1"
  local result="$2"
  local detail="$3"
  print -- "$result  $label — $detail"
  if [[ "$result" == 'FAIL' ]]; then
    ((failures += 1))
  elif [[ "$result" == 'WARN' ]]; then
    ((warnings += 1))
  fi
}

if [[ "$(/bin/pwd -P)" != "$PROJECT_DIR" ]]; then
  print -u2 -- "ERROR: Run this script from $PROJECT_DIR"
  exit 1
fi

exec > "$REPORT_PATH" 2>&1
print_header

section 'PROJECT PREREQUISITES'
for directory in $REQUIRED_PROJECT_DIRS; do
  if [[ -d "$PROJECT_DIR/$directory" ]]; then
    record_check "Project directory: $directory" 'PASS' 'exists'
  else
    record_check "Project directory: $directory" 'FAIL' 'missing'
  fi
done

for target in $EXPECTED_TARGETS; do
  if [[ -d "$PROJECT_DIR/inventory/$target" ]]; then
    record_check "Inventory staging directory: $target" 'PASS' 'exists'
  else
    record_check "Inventory staging directory: $target" 'FAIL' 'missing'
  fi
done

section 'CONFIGURATION AND TEMPLATE'
if [[ -f "$CONFIG_PATH" ]]; then
  record_check 'Inventory target configuration' 'PASS' 'exists'
else
  record_check 'Inventory target configuration' 'FAIL' 'missing'
fi

if [[ -f "$TEMPLATE_PATH" ]]; then
  record_check 'Inventory report template' 'PASS' 'exists'
else
  record_check 'Inventory report template' 'FAIL' 'missing'
fi

if [[ -w "$PROJECT_DIR" && -w "$PROJECT_DIR/reports" ]]; then
  record_check 'Project report write permission' 'PASS' 'available'
else
  record_check 'Project report write permission' 'FAIL' 'unavailable'
fi

section 'CONFIGURED TARGET PATH VALIDATION'
if [[ -f "$CONFIG_PATH" ]]; then
  for target in $EXPECTED_TARGETS; do
    path="$(/usr/bin/awk -v name="$target" '
      $0 == name ":" { found=1; next }
      found && $1 == "path:" { print substr($0, index($0, ":") + 2); exit }
      found && /^[^[:space:]]/ { exit }
    ' "$CONFIG_PATH")"

    if [[ -z "$path" ]]; then
      record_check "Target: $target" 'FAIL' 'missing path configuration'
    elif [[ -d "$path" ]]; then
      record_check "Target: $target" 'PASS' "path exists: $path"
    else
      record_check "Target: $target" 'WARN' "path unavailable: $path"
    fi
  done
else
  record_check 'Configured target paths' 'FAIL' 'configuration unavailable'
fi

section 'READINESS RESULT'
print -- "Failures: $failures"
print -- "Warnings: $warnings"
if (( failures == 0 )); then
  print -- 'READY: The framework is ready for a separately approved future inventory task.'
  print -- 'No target folder was listed, scanned, or inventoried by this readiness check.'
else
  print -- 'NOT READY: Resolve failed framework prerequisites before any inventory task.'
fi
